version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "dependabot"
    labels:
      - "dependencies"
      - "security"
    reviewers:
      - "stangahh"
    versioning-strategy: increase

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"